name: Sync to Upstream

on:
  schedule:
    - cron:  '12 15 * * 1,2,3'
    # scheduled at 07:12 every Monday and Thursday
  workflow_dispatch:
env:
 DOWNSTREAM_BRANCH: ""
  # Optional fetch arguments
 FETCH_ARGS: ""
  # Optional merge arguments
 MERGE_ARGS: ""
  # Optional push arguments
 PUSH_ARGS: ""
  # Optional toggle to spawn time logs (keeps action active) 
 SPAWN_LOGS: "false" # "true" or "false"
jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: Sync HEAD with upstream latest

    steps:
    # Step 1: run a standard checkout action, provided by github
    - name: Checkout HEAD
      uses: dabreadman/sync-upstream-repo@v1.3.0
      with:
        ref: main

    # Step 2: run this sync action - specify the upstream repo, upstream branch to sync with, and target sync branch
    - name: Pull upstream changes
      id: sync
      uses: bdougie/Fork-Sync-With-Upstream-action@fork
      with:
       
        upstream_repository: YgorXavierS/ProjetoPython
        downstream_branch: ${{ env.DOWNSTREAM_BRANCH }}
        fetch_args: ${{ env.FETCH_ARGS }}
        merge_args: ${{ env.MERGE_ARGS }}
        push_args: ${{ env.PUSH_ARGS }}
        spawn_logs: ${{ env.SPAWN_LOGS }}
        
        upstream_branch: main
        target_branch: main
 
        
