name: Sync to Upstream

on:
  schedule:
    - cron:  '12 15 * * 1,2,3'
    # scheduled at 07:12 every Monday and Thursday
  workflow_dispatch:

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: Sync HEAD with upstream latest

    steps:
    # Step 1: run a standard checkout action, provided by github
    - name: Checkout HEAD
      uses:  actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675
      with:
        ref: main

    # Step 2: run this sync action - specify the upstream repo, upstream branch to sync with, and target sync branch
    - name: Pull upstream changes
      id: sync
      uses: bdougie/Fork-Sync-With-Upstream-action@fork
      with:
       
        upstream_repository: YgorXavierS/ProjetoPython
        upstream_branch: main
        target_branch: main
        git_pull_args: --ff-only 
        git config pull.rebase: false 
      
        
